# Makefile
# DSCI GROUP 11, Mar 2023

# This script generates data, models, graphs and tables required for the
# report of wine quality analysis, and also generates the report in html
# format. 

# example usage:
# make all - running this command in the terminal will generate everything needed for the report
# make clean - running this will remove everything that generated by the makefile

all: load cleansplit eda scores html

#load the data
load: src/load.py
	python src/load.py data/raw_data.csv

# clean and split the data
cleansplit: load src/cleansplit.py
	python src/cleansplit.py data/raw_data.csv

# conduct eda
eda: src/eda.py cleansplit
	mkdir results
	python src/eda.py data/train.csv results/eda_

# generate graphs for model comparison
scores: src/scores.py cleansplit
	python src/scores.py data/train.csv data/test.csv results/

# generate the report in html format
html:
# jupyter nbconvert --to html --no-input --execute wineclassification.ipynb --output report.html --ExecutePreprocessor.timeout=-1
	quarto render wineclassification.ipynb --to html

# clean all generated data, graphs, table and the report
clean:
	rm -rf results/
	rm -rf data/raw_data.csv data/test.csv data/train.csv
	rm -rf report.html
